# Load Dependencies

In [2]:
import pandas as pd
import numpy as np
import os

# How to Load Data

## Creating dataframes from scratch

In [3]:
# Create a dataframe from scratch
data = {
    'name': ['John', 'Anna', 'Peter', 'Linda'],
    'location': ['New York', 'Paris', 'Berlin', 'London'],
    'age': [24, 13, 53, 33]
}
df = pd.DataFrame(data)
df

    name  location  age
0   John  New York   24
1   Anna     Paris   13
2  Peter    Berlin   53
3  Linda    London   33

## Loading CSV Files

In [4]:
# Load a sample CSV file using the `read_csv` method. Excel files can similarly be loaded using `read_excel`.
df = pd.read_csv(os.path.join('..', '99_Resources', 'test_scores_example_data.csv'))
df

  student_name  test_score   age           program       college     state
0        Renad        90.0  18.0  Computer Science   Engineering      Ohio
1          Sam        53.0  21.0             Media  Liberal Arts      Ohio
2        Tariq        81.0   NaN             Civil   Engineering  Illinois
3        Caleb        78.0  22.0     Communication  Liberal Arts      Ohio
4       Sereen        94.0  19.0             Media  Liberal Arts  Illinois
5        Layla        82.0  21.0  Computer Science   Engineering      Ohio
6         John         NaN  22.0             Civil   Engineering  Illinois
7         Anna        96.0  20.0             Civil   Engineering      Ohio
8        Peter         NaN  19.0               NaN  Liberal Arts      Ohio
9        Linda        94.0  22.0  Computer Science   Engineering  Illinois

# Data Diagnostics

In [5]:
# Display the number of rows and columns in the dataframe
df.shape

(10, 6)

In [6]:
# General information about the data, including the number of non-null entries and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_name  10 non-null     object
 1   test_score    8 non-null      float64
 2   age           9 non-null      float64
 3   program       9 non-null      object
 4   college       10 non-null     object
 5   state         10 non-null     object
dtypes: float64(2), object(4)
memory usage: 608.0+ bytes

In [7]:
# Compute basic statistics for numeric columns
df.describe()

       test_score        age
count    8.000000   9.000000
mean    83.500000  20.444444
std     14.081396   1.509231
min     53.000000  18.000000
25%     80.250000  19.000000
50%     86.000000  21.000000
75%     94.000000  22.000000
max     96.000000  22.000000

In [8]:
# List all unique values and their counts in a specific column
df['program'].value_counts(dropna=False) # The dropna=False argument includes NaN values in the count

program
Computer Science    3
Civil               3
Media               2
Communication       1
NaN                 1
Name: count, dtype: int64

In [9]:
# Compute the median and mean of the 'test_score' column
print("Median and Mean of test_score:")
print(f'- Median:  {df['test_score'].median()}')
print(f'- Mean:    {df['test_score'].mean()}')

SyntaxError: f-string: unmatched '[' (2540854769.py, line 3)

# Selecting and Filtering Data

## Selecting Columns

In [10]:
# How do we slice and dice the data?
# We can select a specific column using the column name and the `[]` operator
df['test_score'] # Note that this outputs a Series

0    90.0
1    53.0
2    81.0
3    78.0
4    94.0
5    82.0
6     NaN
7    96.0
8     NaN
9    94.0
Name: test_score, dtype: float64

In [11]:
# We can also select multiple columns by passing a list of column names
df[['student_name', 'test_score']] # Note that this outputs a DataFrame

  student_name  test_score
0        Renad        90.0
1          Sam        53.0
2        Tariq        81.0
3        Caleb        78.0
4       Sereen        94.0
5        Layla        82.0
6         John         NaN
7         Anna        96.0
8        Peter         NaN
9        Linda        94.0

## Selecting Rows
How about selecting rows? We can do this a few different ways.

### 1. Using `iloc`

In [12]:
# `iloc` selects rows by absolute index number - remember, Python uses zero-based indexing!
df.iloc[0] # Select the first row
df.iloc[-1] # Select the last row
df.iloc[1:3] # Select the second and third rows

  student_name  test_score   age program       college     state
1          Sam        53.0  21.0   Media  Liberal Arts      Ohio
2        Tariq        81.0   NaN   Civil   Engineering  Illinois

### 2. Using `loc`

In [13]:
# `loc` selects rows by their actual unique label
# If the index is not set, the default index is just a range of integers starting from 0, 
# so the `loc` method behaves similarly to the `iloc` method
df.loc[0] # Select the first row
df.loc[1:3] # Select the second, third, AND fourth rows - this is inclusive of the last index!
# Note that using `-1` like with iloc doesn't make sense, since this is based on index 
# labels, not positions

  student_name  test_score   age        program       college     state
1          Sam        53.0  21.0          Media  Liberal Arts      Ohio
2        Tariq        81.0   NaN          Civil   Engineering  Illinois
3        Caleb        78.0  22.0  Communication  Liberal Arts      Ohio

### 3. Boolean Masks

In [14]:
# Boolean indexing selects rows based on a logical condition
# For example, we can select all rows where the test score is greater than or equal to 
# 90 by creating a boolean mask with a logical operator
mask = df['test_score'] >= 90

# We can then use this mask to filter the dataframe. Note that this uses the same `[]` 
# operator as before, but now we are passing a boolean mask instead of a column name. 
# Don't worry, Python will know the difference!
df[mask] # Select all rows where the test score is greater than 90

# This is equivalent to the following:
df.loc[mask]
df.loc[df['test_score'] >= 90] # All at once is a great way to do it!

  student_name  test_score   age           program       college     state
0        Renad        90.0  18.0  Computer Science   Engineering      Ohio
4       Sereen        94.0  19.0             Media  Liberal Arts  Illinois
7         Anna        96.0  20.0             Civil   Engineering      Ohio
9        Linda        94.0  22.0  Computer Science   Engineering  Illinois

In [15]:
# We can also use the `&` operator to combine multiple conditions
# For example, we can select all rows where the test score is greater than or equal to
# 90 AND the student age is less then 20
df[(df['test_score'] >= 90) & (df['age'] < 20)]

  student_name  test_score   age           program       college     state
0        Renad        90.0  18.0  Computer Science   Engineering      Ohio
4       Sereen        94.0  19.0             Media  Liberal Arts  Illinois

In [16]:
# We can also use the `isin` method to select rows based on a list of values
# This is useful when you want to filter the dataframe based on multiple values in a column,
# such as selecting from categorical columns
df[df['program'].isin(['Engineering', 'Media'])]

  student_name  test_score   age program       college     state
1          Sam        53.0  21.0   Media  Liberal Arts      Ohio
4       Sereen        94.0  19.0   Media  Liberal Arts  Illinois

### 4. Using `query`

In [17]:
# The `query` method selects rows based on a condition expressed as a string
# This is a more readable way to filter the dataframe using a string expression, and 
# may be more intuitive for users familiar with SQL
df.query('test_score >= 90 and age < 20')

  student_name  test_score   age           program       college     state
0        Renad        90.0  18.0  Computer Science   Engineering      Ohio
4       Sereen        94.0  19.0             Media  Liberal Arts  Illinois

# Data Cleanup

In [18]:
# We can drop rows with missing data
df.dropna(axis=0)

  student_name  test_score   age           program       college     state
0        Renad        90.0  18.0  Computer Science   Engineering      Ohio
1          Sam        53.0  21.0             Media  Liberal Arts      Ohio
3        Caleb        78.0  22.0     Communication  Liberal Arts      Ohio
4       Sereen        94.0  19.0             Media  Liberal Arts  Illinois
5        Layla        82.0  21.0  Computer Science   Engineering      Ohio
7         Anna        96.0  20.0             Civil   Engineering      Ohio
9        Linda        94.0  22.0  Computer Science   Engineering  Illinois

In [19]:
# We can fill missing data with assumed values
df = df.fillna(value={'test_score': 50, 'age': df.age.median(), 'program': 'Undeclared'})
df

  student_name  test_score   age           program       college     state
0        Renad        90.0  18.0  Computer Science   Engineering      Ohio
1          Sam        53.0  21.0             Media  Liberal Arts      Ohio
2        Tariq        81.0  21.0             Civil   Engineering  Illinois
3        Caleb        78.0  22.0     Communication  Liberal Arts      Ohio
4       Sereen        94.0  19.0             Media  Liberal Arts  Illinois
5        Layla        82.0  21.0  Computer Science   Engineering      Ohio
6         John        50.0  22.0             Civil   Engineering  Illinois
7         Anna        96.0  20.0             Civil   Engineering      Ohio
8        Peter        50.0  19.0        Undeclared  Liberal Arts      Ohio
9        Linda        94.0  22.0  Computer Science   Engineering  Illinois

## Updating Data

In [20]:
# We can add new columns to the dataframe using the `[]` operator
# For example, we can add a new column called 'pass' that indicates whether the student
# passed the test (score >= 60)
df['pass'] = df['test_score'] >= 60
df

,student_name,test_score,age,program,college,state,pass
0,Renad,90.0,18.0,Computer Science,Engineering,Ohio,True
1,Sam,53.0,21.0,Media,Liberal Arts,Ohio,False
2,Tariq,81.0,21.0,Civil,Engineering,Illinois,True
3,Caleb,78.0,22.0,Communication,Liberal Arts,Ohio,True
4,Sereen,94.0,19.0,Media,Liberal Arts,Illinois,True
5,Layla,82.0,21.0,Computer Science,Engineering,Ohio,True
6,John,50.0,22.0,Civil,Engineering,Illinois,False
7,Anna,96.0,20.0,Civil,Engineering,Ohio,True
8,Peter,50.0,19.0,Undeclared,Liberal Arts,Ohio,False
9,Linda,94.0,22.0,Computer Science,Engineering,Illinois,True

In [21]:
# We can also drop columns from the dataframe using the `drop` method
# For example, we can drop the 'pass' column we just created
df.drop(columns=['pass']) # This returns a new dataframe without the 'pass' column

  student_name  test_score   age           program       college     state
0        Renad        90.0  18.0  Computer Science   Engineering      Ohio
1          Sam        53.0  21.0             Media  Liberal Arts      Ohio
2        Tariq        81.0  21.0             Civil   Engineering  Illinois
3        Caleb        78.0  22.0     Communication  Liberal Arts      Ohio
4       Sereen        94.0  19.0             Media  Liberal Arts  Illinois
5        Layla        82.0  21.0  Computer Science   Engineering      Ohio
6         John        50.0  22.0             Civil   Engineering  Illinois
7         Anna        96.0  20.0             Civil   Engineering      Ohio
8        Peter        50.0  19.0        Undeclared  Liberal Arts      Ohio
9        Linda        94.0  22.0  Computer Science   Engineering  Illinois

In [ ]:
# We can identify duplicates in the dataframe using the `duplicated` method
# This is useful for identifying rows that are identical in all columns
# Note that this method returns a boolean Series indicating which rows are duplicates
df.duplicated() # This returns a boolean Series indicating which rows are duplicates
# Any duplicates rturned? Use df.drop_duplicates(). This returns a new dataframe without the duplicate rows if they exist

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

# Data Grouping

In [21]:
# Grouping data is a powerful feature of pandas and makes it easy to perform
# aggregations on the data
# For example, we can group the data by the 'program' column and compute the median
# test score for each program
grouped = df.groupby('program')['test_score'].median()
grouped

program
Civil               81.0
Communication       78.0
Computer Science    90.0
Media               73.5
Undeclared          50.0
Name: test_score, dtype: float64

In [28]:
# We can also group by multiple columns
grouped = df.groupby(['program', 'state'])['test_score'].median()
grouped

program           state
Civil             Illinois    65.5
                  Ohio        96.0
Communication     Ohio        78.0
Computer Science  Illinois    94.0
                  Ohio        86.0
Media             Illinois    94.0
                  Ohio        53.0
Undeclared        Ohio        50.0
Name: test_score, dtype: float64

In [33]:
# Groupbys can be turned into pivot tables by "unstacking" the data
df.groupby(['program', 'state']).size().unstack().fillna(0).astype(int)

state             Illinois  Ohio
program
Civil                    2     1
Communication            0     1
Computer Science         1     2
Media                    1     1
Undeclared               0     1

# Merging Data

## Horizontal Joins

In [43]:
# There are a variety of ways that we can merge dataframes together
# For example, we can use the `merge` method to combine two dataframes based on a common column
# or index, similar to SQL joins
# For the sake of example, let's merge the test dataframe with a copy of itself
df.merge(df, left_index=True, right_index=True, suffixes=('', '_right'))

,student_name,test_score,age,program,college,state,pass,student_name_right,test_score_right,age_right,program_right,college_right,state_right,pass_right
0,Renad,90.0,18.0,Computer Science,Engineering,Ohio,True,Renad,90.0,18.0,Computer Science,Engineering,Ohio,True
1,Sam,53.0,21.0,Media,Liberal Arts,Ohio,False,Sam,53.0,21.0,Media,Liberal Arts,Ohio,False
2,Tariq,81.0,21.0,Civil,Engineering,Illinois,True,Tariq,81.0,21.0,Civil,Engineering,Illinois,True
3,Caleb,78.0,22.0,Communication,Liberal Arts,Ohio,True,Caleb,78.0,22.0,Communication,Liberal Arts,Ohio,True
4,Sereen,94.0,19.0,Media,Liberal Arts,Illinois,True,Sereen,94.0,19.0,Media,Liberal Arts,Illinois,True
5,Layla,82.0,21.0,Computer Science,Engineering,Ohio,True,Layla,82.0,21.0,Computer Science,Engineering,Ohio,True
6,John,50.0,22.0,Civil,Engineering,Illinois,False,John,50.0,22.0,Civil,Engineering,Illinois,False
7,Anna,96.0,20.0,Civil,Engineering,Ohio,True,Anna,96.0,20.0,Civil,Engineering,Ohio,True
8,Peter,50.0,19.0,Undeclared,Liberal Arts,Ohio,False,Peter,50.0,19.0,Undeclared,Liberal Arts,Ohio,False
9,Linda,94.0,22.0,Computer Science,Engineering,Illinois,True,Linda,94.0,22.0,Computer Science,Engineering,Illinois,True

## Vertical Joins

In [38]:
# We can also use the `concat` method to concatenate multiple dataframes along a particular axis
# matching the index or columns
# For example, we can concatenate two dataframes vertically
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
df_concat = pd.concat([df1, df2], axis=0, ignore_index=True)
df_concat

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

# Exporting Data

## Basic Exports

In [ ]:
# Let's export to CSV
# Choose a filepath to export the data to
fp = 'sample_data.csv'
# Export the dataframe to a CSV file
df.to_csv(fp, index=False) # Do you want to include the index? (default is True)

## Advanced Exports

In [ ]:
# Let's export to Excel, using separate sheets for each unique program
# Choose a filepath to export the data to
fp = 'sample_data.xlsx'

# Identify all unique programs
unique_programs = df['program'].unique()

# We first need to create a Pandas Excel writer using XlsxWriter as the engine
# This will allow us to write multiple sheets to the same file
# The `with` statement ensures that the file is properly saved and closed
with pd.ExcelWriter('example_export.xlsx') as writer:
    # Loop through each unique program
    for program in unique_programs:
        # Filter the dataframe for the current program
        df_program = df[df['program'] == program]
        # Write the dataframe to a sheet named after the program
        df_program.to_excel(writer, sheet_name=program, index=False)